name: assignment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio:
  get_it:
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0 # Correctly placed here, not under sdk: flutter
  mockito: ^5.0.0 # Correctly placed here, not under sdk: flutter
  flutter_lints: ^3.0.0 # Correctly placed here, not under sdk: flutter

flutter:
  uses-material-design: true